### PR TITLE
fix: add updated and created for link type

### PR DESCRIPTION
**Pull request by EstebanBorai**

### CODE REVIEW

**Review by Michael-Liendo — COMMENTED** [review]
Ohh very good, do you think the expiration date could be added?

**Comment by EstebanBorai** [comment]
> 

Expiration date is deprecated now. Perhaps we can reintroduce it in the future but it needs certain logic which is not implemented

**Comment by EstebanBorai** [comment]
@Michael-Liendo feel free to open an issue on expiration dates, we can review it in the future!

**Comment by Michael-Liendo** [comment]
> > Ohh very good, do you think the expiration date could be added?
> 
> Expiration date is deprecated now. Perhaps we can reintroduce it in the future but it needs certain logic which is not implemented

Oh I understand, yes in the future it could be

**Pull request merged**
